#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 143
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 2

enum {
  sym_identifier = 1,
  anon_sym_payable = 2,
  anon_sym_contract = 3,
  anon_sym_EQ = 4,
  anon_sym_entrypoint = 5,
  anon_sym_function = 6,
  anon_sym_stateful = 7,
  anon_sym_private = 8,
  anon_sym_COLON = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_RPAREN = 12,
  anon_sym_EQ_GT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_type = 18,
  anon_sym_record = 19,
  anon_sym_LBRACE = 20,
  anon_sym_RBRACE = 21,
  anon_sym_unit = 22,
  sym_constructor = 23,
  anon_sym_DOT = 24,
  anon_sym_SQUOTE = 25,
  sym_int = 26,
  sym_comment = 27,
  sym__indent = 28,
  sym__dedent = 29,
  sym__newline = 30,
  sym_source_file = 31,
  sym__top_declaration = 32,
  sym_contract_declaration = 33,
  sym__declaration = 34,
  sym_entrypoint_modifier = 35,
  sym_function_modifier = 36,
  sym_function_declaration = 37,
  sym_arguments = 38,
  sym_statement = 39,
  sym_pattern = 40,
  sym_expression = 41,
  sym_binary_operator = 42,
  sym__type_declaration = 43,
  sym__record_declaration = 44,
  sym__type_alias = 45,
  sym_record_type = 46,
  sym_field_type = 47,
  sym_type = 48,
  sym_domain = 49,
  sym_qualified_identifier = 50,
  sym_type_variable = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_contract_declaration_repeat1 = 53,
  aux_sym_function_declaration_repeat1 = 54,
  aux_sym_arguments_repeat1 = 55,
  aux_sym_record_type_repeat1 = 56,
  aux_sym_constructor_declaration_repeat1 = 57,
  aux_sym_qualified_identifier_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_payable] = "payable",
  [anon_sym_contract] = "contract",
  [anon_sym_EQ] = "=",
  [anon_sym_entrypoint] = "entrypoint",
  [anon_sym_function] = "function",
  [anon_sym_stateful] = "stateful",
  [anon_sym_private] = "private",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_type] = "type",
  [anon_sym_record] = "record",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_unit] = "unit",
  [sym_constructor] = "constructor",
  [anon_sym_DOT] = ".",
  [anon_sym_SQUOTE] = "'",
  [sym_int] = "int",
  [sym_comment] = "comment",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym__top_declaration] = "_top_declaration",
  [sym_contract_declaration] = "contract_declaration",
  [sym__declaration] = "_declaration",
  [sym_entrypoint_modifier] = "entrypoint_modifier",
  [sym_function_modifier] = "function_modifier",
  [sym_function_declaration] = "function_declaration",
  [sym_arguments] = "arguments",
  [sym_statement] = "statement",
  [sym_pattern] = "pattern",
  [sym_expression] = "expression",
  [sym_binary_operator] = "binary_operator",
  [sym__type_declaration] = "_type_declaration",
  [sym__record_declaration] = "_record_declaration",
  [sym__type_alias] = "_type_alias",
  [sym_record_type] = "record_type",
  [sym_field_type] = "field_type",
  [sym_type] = "type",
  [sym_domain] = "domain",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_type_variable] = "type_variable",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_contract_declaration_repeat1] = "contract_declaration_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_record_type_repeat1] = "record_type_repeat1",
  [aux_sym_constructor_declaration_repeat1] = "constructor_declaration_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_payable] = anon_sym_payable,
  [anon_sym_contract] = anon_sym_contract,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_entrypoint] = anon_sym_entrypoint,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_stateful] = anon_sym_stateful,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_unit] = anon_sym_unit,
  [sym_constructor] = sym_constructor,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_int] = sym_int,
  [sym_comment] = sym_comment,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym__top_declaration] = sym__top_declaration,
  [sym_contract_declaration] = sym_contract_declaration,
  [sym__declaration] = sym__declaration,
  [sym_entrypoint_modifier] = sym_entrypoint_modifier,
  [sym_function_modifier] = sym_function_modifier,
  [sym_function_declaration] = sym_function_declaration,
  [sym_arguments] = sym_arguments,
  [sym_statement] = sym_statement,
  [sym_pattern] = sym_pattern,
  [sym_expression] = sym_expression,
  [sym_binary_operator] = sym_binary_operator,
  [sym__type_declaration] = sym__type_declaration,
  [sym__record_declaration] = sym__record_declaration,
  [sym__type_alias] = sym__type_alias,
  [sym_record_type] = sym_record_type,
  [sym_field_type] = sym_field_type,
  [sym_type] = sym_type,
  [sym_domain] = sym_domain,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_type_variable] = sym_type_variable,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_contract_declaration_repeat1] = aux_sym_contract_declaration_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_record_type_repeat1] = aux_sym_record_type_repeat1,
  [aux_sym_constructor_declaration_repeat1] = aux_sym_constructor_declaration_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_payable] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_entrypoint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stateful] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unit] = {
    .visible = true,
    .named = false,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_contract_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_entrypoint_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym__type_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__record_declaration] = {
    .visible = false,
    .named = true,
  },
  [sym__type_alias] = {
    .visible = false,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym_field_type] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_contract_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constructor_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '.') ADVANCE(31);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '0') ADVANCE(33);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == '=') ADVANCE(17);
      if (lookahead == '\\') SKIP(14)
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == 8203 ||
          lookahead == 8288 ||
          lookahead == 65279) SKIP(0)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(5)
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(5)
      if (lookahead == '\r') SKIP(1)
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(6)
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '\r') SKIP(3)
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '+') ADVANCE(23);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '\\') SKIP(2)
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == 8203 ||
          lookahead == 8288 ||
          lookahead == 65279) SKIP(5)
      END_STATE();
    case 6:
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == '/') ADVANCE(7);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '\\') SKIP(4)
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == 8203 ||
          lookahead == 8288 ||
          lookahead == 65279) SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(13)
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_constructor);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'x') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '_') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '_') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\\') SKIP(1)
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 'r') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\f' ||
          lookahead == '\r' ||
          lookahead == ' ' ||
          lookahead == 8203 ||
          lookahead == 8288 ||
          lookahead == 65279) SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(0)
      if (lookahead == '\r') SKIP(10)
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == '\n') SKIP(0)
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'y') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(27);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 24:
      if (lookahead == 'v') ADVANCE(33);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'y') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'b') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_unit);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(46);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(48);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 52:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_payable);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_contract);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_stateful);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_entrypoint);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 5, .external_lex_state = 4},
  [36] = {.lex_state = 5, .external_lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 5, .external_lex_state = 4},
  [39] = {.lex_state = 5, .external_lex_state = 4},
  [40] = {.lex_state = 5, .external_lex_state = 4},
  [41] = {.lex_state = 5, .external_lex_state = 4},
  [42] = {.lex_state = 5, .external_lex_state = 4},
  [43] = {.lex_state = 5, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 5, .external_lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0, .external_lex_state = 4},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 0, .external_lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 5, .external_lex_state = 4},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 5, .external_lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0, .external_lex_state = 4},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0, .external_lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 4},
  [106] = {.lex_state = 0, .external_lex_state = 4},
  [107] = {.lex_state = 5},
  [108] = {.lex_state = 6},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0, .external_lex_state = 4},
  [111] = {.lex_state = 6},
  [112] = {.lex_state = 0, .external_lex_state = 4},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 0, .external_lex_state = 4},
  [115] = {.lex_state = 0, .external_lex_state = 4},
  [116] = {.lex_state = 6},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 0, .external_lex_state = 4},
  [119] = {.lex_state = 0, .external_lex_state = 4},
  [120] = {.lex_state = 0, .external_lex_state = 4},
  [121] = {.lex_state = 0, .external_lex_state = 4},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0, .external_lex_state = 4},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 5},
  [129] = {.lex_state = 6},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 5},
  [132] = {.lex_state = 0, .external_lex_state = 3},
  [133] = {.lex_state = 0, .external_lex_state = 3},
  [134] = {.lex_state = 6},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 5},
  [137] = {.lex_state = 6},
  [138] = {.lex_state = 6},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
};

enum {
  ts_external_token__indent = 0,
  ts_external_token__dedent = 1,
  ts_external_token__newline = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__newline] = sym__newline,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__newline] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token__indent] = true,
  },
  [4] = {
    [ts_external_token__newline] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_payable] = ACTIONS(1),
    [anon_sym_contract] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_entrypoint] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_stateful] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_unit] = ACTIONS(1),
    [sym_constructor] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(140),
    [sym__top_declaration] = STATE(56),
    [sym_contract_declaration] = STATE(56),
    [aux_sym_source_file_repeat1] = STATE(56),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_payable] = ACTIONS(7),
    [anon_sym_contract] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_payable,
    ACTIONS(15), 1,
      anon_sym_stateful,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      anon_sym_record,
    ACTIONS(23), 1,
      sym__dedent,
    STATE(4), 1,
      aux_sym_contract_declaration_repeat1,
    STATE(122), 1,
      sym_function_modifier,
    STATE(123), 1,
      sym_entrypoint_modifier,
    ACTIONS(13), 2,
      anon_sym_entrypoint,
      anon_sym_function,
    STATE(124), 3,
      sym__declaration,
      sym__type_declaration,
      sym__record_declaration,
  [40] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_payable,
    ACTIONS(15), 1,
      anon_sym_stateful,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      anon_sym_record,
    ACTIONS(25), 1,
      sym__dedent,
    STATE(4), 1,
      aux_sym_contract_declaration_repeat1,
    STATE(122), 1,
      sym_function_modifier,
    STATE(123), 1,
      sym_entrypoint_modifier,
    ACTIONS(13), 2,
      anon_sym_entrypoint,
      anon_sym_function,
    STATE(124), 3,
      sym__declaration,
      sym__type_declaration,
      sym__record_declaration,
  [80] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_payable,
    ACTIONS(33), 1,
      anon_sym_stateful,
    ACTIONS(36), 1,
      anon_sym_private,
    ACTIONS(39), 1,
      anon_sym_type,
    ACTIONS(42), 1,
      anon_sym_record,
    ACTIONS(45), 1,
      sym__dedent,
    STATE(4), 1,
      aux_sym_contract_declaration_repeat1,
    STATE(122), 1,
      sym_function_modifier,
    STATE(123), 1,
      sym_entrypoint_modifier,
    ACTIONS(30), 2,
      anon_sym_entrypoint,
      anon_sym_function,
    STATE(124), 3,
      sym__declaration,
      sym__type_declaration,
      sym__record_declaration,
  [120] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_payable,
    ACTIONS(15), 1,
      anon_sym_stateful,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      anon_sym_record,
    ACTIONS(47), 1,
      sym__dedent,
    STATE(3), 1,
      aux_sym_contract_declaration_repeat1,
    STATE(122), 1,
      sym_function_modifier,
    STATE(123), 1,
      sym_entrypoint_modifier,
    ACTIONS(13), 2,
      anon_sym_entrypoint,
      anon_sym_function,
    STATE(124), 3,
      sym__declaration,
      sym__type_declaration,
      sym__record_declaration,
  [160] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_payable,
    ACTIONS(15), 1,
      anon_sym_stateful,
    ACTIONS(17), 1,
      anon_sym_private,
    ACTIONS(19), 1,
      anon_sym_type,
    ACTIONS(21), 1,
      anon_sym_record,
    ACTIONS(25), 1,
      sym__dedent,
    STATE(2), 1,
      aux_sym_contract_declaration_repeat1,
    STATE(122), 1,
      sym_function_modifier,
    STATE(123), 1,
      sym_entrypoint_modifier,
    ACTIONS(13), 2,
      anon_sym_entrypoint,
      anon_sym_function,
    STATE(124), 3,
      sym__declaration,
      sym__type_declaration,
      sym__record_declaration,
  [200] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [233] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    ACTIONS(59), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [266] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    STATE(63), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [299] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(84), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(103), 1,
      sym__type_alias,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [332] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [365] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(84), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(114), 1,
      sym__type_alias,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [398] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(84), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(118), 1,
      sym__type_alias,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [431] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(70), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [461] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [491] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [521] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(33), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [551] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(69), 8,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [571] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(69), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [589] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(69), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [607] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_constructor,
    ACTIONS(79), 1,
      sym__dedent,
    STATE(29), 1,
      aux_sym_function_declaration_repeat1,
    STATE(61), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(101), 1,
      sym_statement,
    ACTIONS(75), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [637] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_SLASH,
    ACTIONS(81), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [655] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(65), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_SQUOTE,
    STATE(40), 1,
      sym_type,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(128), 1,
      sym_domain,
    ACTIONS(63), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(43), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [685] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SLASH,
    ACTIONS(85), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [703] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(18), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [733] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SLASH,
    ACTIONS(89), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [751] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      sym_type,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(136), 1,
      sym_domain,
    ACTIONS(49), 2,
      anon_sym_unit,
      sym_identifier,
    STATE(28), 2,
      sym_qualified_identifier,
      sym_type_variable,
  [781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(93), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [799] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_constructor,
    ACTIONS(97), 1,
      sym__dedent,
    STATE(31), 1,
      aux_sym_function_declaration_repeat1,
    STATE(61), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(101), 1,
      sym_statement,
    ACTIONS(75), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [829] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    ACTIONS(99), 9,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RBRACE,
  [847] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_constructor,
    ACTIONS(109), 1,
      sym__dedent,
    STATE(31), 1,
      aux_sym_function_declaration_repeat1,
    STATE(61), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(101), 1,
      sym_statement,
    ACTIONS(103), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [877] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_constructor,
    ACTIONS(111), 1,
      sym__indent,
    STATE(61), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(100), 1,
      sym_statement,
    ACTIONS(75), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [904] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    ACTIONS(113), 6,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [925] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RPAREN,
    ACTIONS(123), 1,
      sym_constructor,
    STATE(51), 1,
      sym_expression,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(87), 1,
      sym_pattern,
    ACTIONS(119), 2,
      sym_identifier,
      sym_int,
    STATE(49), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [952] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(69), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [968] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(69), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [984] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_constructor,
    STATE(51), 1,
      sym_expression,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    STATE(90), 1,
      sym_pattern,
    ACTIONS(119), 2,
      sym_identifier,
      sym_int,
    STATE(49), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [1008] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_SLASH,
    ACTIONS(99), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1024] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SLASH,
    ACTIONS(85), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1040] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 5,
      sym__newline,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1060] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_SLASH,
    ACTIONS(89), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1076] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_SLASH,
    ACTIONS(81), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(93), 7,
      sym__newline,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1108] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 8,
      sym__dedent,
      anon_sym_payable,
      anon_sym_entrypoint,
      anon_sym_function,
      anon_sym_stateful,
      anon_sym_private,
      anon_sym_type,
      anon_sym_record,
  [1122] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SLASH,
    ACTIONS(131), 1,
      anon_sym_DOT,
    ACTIONS(127), 6,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1140] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 6,
      sym__newline,
      anon_sym_COLON,
      anon_sym_EQ_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1158] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_constructor,
    STATE(59), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(75), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [1179] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_STAR,
    ACTIONS(137), 1,
      anon_sym_SLASH,
    ACTIONS(133), 5,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1196] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SLASH,
    ACTIONS(127), 6,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1211] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(133), 6,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1226] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_STAR,
    ACTIONS(137), 1,
      anon_sym_SLASH,
    ACTIONS(141), 1,
      anon_sym_COLON,
    ACTIONS(143), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(145), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1247] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SLASH,
    ACTIONS(131), 1,
      anon_sym_DOT,
    ACTIONS(127), 5,
      sym__newline,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1264] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_constructor,
    STATE(57), 1,
      sym_expression,
    STATE(86), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(75), 2,
      sym_identifier,
      sym_int,
    STATE(60), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [1285] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_constructor,
    STATE(50), 1,
      sym_expression,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(119), 2,
      sym_identifier,
      sym_int,
    STATE(49), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [1306] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_constructor,
    STATE(48), 1,
      sym_expression,
    STATE(72), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(119), 2,
      sym_identifier,
      sym_int,
    STATE(49), 2,
      sym_binary_operator,
      sym_qualified_identifier,
  [1327] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_payable,
    ACTIONS(9), 1,
      anon_sym_contract,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
    STATE(58), 3,
      sym__top_declaration,
      sym_contract_declaration,
      aux_sym_source_file_repeat1,
  [1345] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(151), 1,
      anon_sym_SLASH,
    ACTIONS(133), 4,
      sym__newline,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1361] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 1,
      anon_sym_payable,
    ACTIONS(158), 1,
      anon_sym_contract,
    STATE(58), 3,
      sym__top_declaration,
      sym_contract_declaration,
      aux_sym_source_file_repeat1,
  [1379] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_SLASH,
    ACTIONS(133), 5,
      sym__newline,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_SLASH,
    ACTIONS(127), 5,
      sym__newline,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
  [1407] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(151), 1,
      anon_sym_SLASH,
    ACTIONS(161), 1,
      anon_sym_COLON,
    ACTIONS(165), 1,
      sym__newline,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1427] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_constructor_declaration_repeat1,
  [1446] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_constructor_declaration_repeat1,
  [1465] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_constructor_declaration_repeat1,
  [1484] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_constructor_declaration_repeat1,
  [1503] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(177), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1517] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_LPAREN,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(179), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1531] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 4,
      sym__dedent,
      sym_identifier,
      sym_constructor,
      sym_int,
  [1541] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_arguments_repeat1,
  [1554] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(185), 1,
      sym__newline,
  [1567] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_constructor_declaration_repeat1,
  [1580] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(89), 1,
      aux_sym_qualified_identifier_repeat1,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_payable,
      anon_sym_contract,
  [1602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_payable,
      anon_sym_contract,
  [1611] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_COLON,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    STATE(111), 1,
      sym_arguments,
  [1624] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_record_type_repeat1,
  [1637] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_field_type,
  [1650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 3,
      ts_builtin_sym_end,
      anon_sym_payable,
      anon_sym_contract,
  [1659] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_constructor_declaration_repeat1,
  [1672] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_SQUOTE,
    ACTIONS(212), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      sym_type_variable,
  [1685] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_constructor_declaration_repeat1,
  [1698] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RBRACE,
    STATE(88), 1,
      aux_sym_record_type_repeat1,
  [1711] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_COMMA,
    ACTIONS(224), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_arguments_repeat1,
  [1724] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_EQ_GT,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    ACTIONS(226), 1,
      sym__newline,
  [1737] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_constructor_declaration_repeat1,
  [1750] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      sym_constructor,
    ACTIONS(230), 1,
      sym_identifier,
    STATE(89), 1,
      aux_sym_qualified_identifier_repeat1,
  [1763] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      aux_sym_arguments_repeat1,
  [1776] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(76), 1,
      aux_sym_record_type_repeat1,
  [1789] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_identifier,
    ACTIONS(238), 1,
      sym_constructor,
    STATE(89), 1,
      aux_sym_qualified_identifier_repeat1,
  [1802] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1818] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 2,
      sym_identifier,
      sym_constructor,
  [1826] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(119), 1,
      sym_function_declaration,
  [1836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_entrypoint,
    ACTIONS(245), 1,
      anon_sym_function,
  [1846] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_EQ,
    ACTIONS(249), 1,
      anon_sym_LPAREN,
  [1856] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
    STATE(121), 1,
      sym_record_type,
  [1866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(105), 1,
      sym_function_declaration,
  [1876] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
    STATE(91), 1,
      sym_field_type,
  [1886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
  [1893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym__newline,
  [1900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym__newline,
  [1907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_identifier,
  [1914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__newline,
  [1921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_DOT,
  [1928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      sym__newline,
  [1935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym__newline,
  [1942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_EQ_GT,
  [1949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_EQ,
  [1956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_COLON,
  [1963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym__newline,
  [1970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_EQ,
  [1977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym__newline,
  [1984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_EQ,
  [1991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym__newline,
  [1998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym__newline,
  [2005] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_EQ,
  [2012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_EQ,
  [2019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym__newline,
  [2026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym__newline,
  [2033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      sym__newline,
  [2040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym__newline,
  [2047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_function,
  [2054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_entrypoint,
  [2061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      sym__newline,
  [2068] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_identifier,
  [2075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
  [2082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_function,
  [2089] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_EQ_GT,
  [2096] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_EQ,
  [2103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_entrypoint,
  [2110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      anon_sym_EQ_GT,
  [2117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      sym__indent,
  [2124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym__indent,
  [2131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_EQ,
  [2138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      sym_identifier,
  [2145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_EQ_GT,
  [2152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_EQ,
  [2159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_EQ,
  [2166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym_constructor,
  [2173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      ts_builtin_sym_end,
  [2180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_contract,
  [2187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(331), 1,
      sym_constructor,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 200,
  [SMALL_STATE(8)] = 233,
  [SMALL_STATE(9)] = 266,
  [SMALL_STATE(10)] = 299,
  [SMALL_STATE(11)] = 332,
  [SMALL_STATE(12)] = 365,
  [SMALL_STATE(13)] = 398,
  [SMALL_STATE(14)] = 431,
  [SMALL_STATE(15)] = 461,
  [SMALL_STATE(16)] = 491,
  [SMALL_STATE(17)] = 521,
  [SMALL_STATE(18)] = 551,
  [SMALL_STATE(19)] = 571,
  [SMALL_STATE(20)] = 589,
  [SMALL_STATE(21)] = 607,
  [SMALL_STATE(22)] = 637,
  [SMALL_STATE(23)] = 655,
  [SMALL_STATE(24)] = 685,
  [SMALL_STATE(25)] = 703,
  [SMALL_STATE(26)] = 733,
  [SMALL_STATE(27)] = 751,
  [SMALL_STATE(28)] = 781,
  [SMALL_STATE(29)] = 799,
  [SMALL_STATE(30)] = 829,
  [SMALL_STATE(31)] = 847,
  [SMALL_STATE(32)] = 877,
  [SMALL_STATE(33)] = 904,
  [SMALL_STATE(34)] = 925,
  [SMALL_STATE(35)] = 952,
  [SMALL_STATE(36)] = 968,
  [SMALL_STATE(37)] = 984,
  [SMALL_STATE(38)] = 1008,
  [SMALL_STATE(39)] = 1024,
  [SMALL_STATE(40)] = 1040,
  [SMALL_STATE(41)] = 1060,
  [SMALL_STATE(42)] = 1076,
  [SMALL_STATE(43)] = 1092,
  [SMALL_STATE(44)] = 1108,
  [SMALL_STATE(45)] = 1122,
  [SMALL_STATE(46)] = 1140,
  [SMALL_STATE(47)] = 1158,
  [SMALL_STATE(48)] = 1179,
  [SMALL_STATE(49)] = 1196,
  [SMALL_STATE(50)] = 1211,
  [SMALL_STATE(51)] = 1226,
  [SMALL_STATE(52)] = 1247,
  [SMALL_STATE(53)] = 1264,
  [SMALL_STATE(54)] = 1285,
  [SMALL_STATE(55)] = 1306,
  [SMALL_STATE(56)] = 1327,
  [SMALL_STATE(57)] = 1345,
  [SMALL_STATE(58)] = 1361,
  [SMALL_STATE(59)] = 1379,
  [SMALL_STATE(60)] = 1393,
  [SMALL_STATE(61)] = 1407,
  [SMALL_STATE(62)] = 1427,
  [SMALL_STATE(63)] = 1446,
  [SMALL_STATE(64)] = 1465,
  [SMALL_STATE(65)] = 1484,
  [SMALL_STATE(66)] = 1503,
  [SMALL_STATE(67)] = 1517,
  [SMALL_STATE(68)] = 1531,
  [SMALL_STATE(69)] = 1541,
  [SMALL_STATE(70)] = 1554,
  [SMALL_STATE(71)] = 1567,
  [SMALL_STATE(72)] = 1580,
  [SMALL_STATE(73)] = 1593,
  [SMALL_STATE(74)] = 1602,
  [SMALL_STATE(75)] = 1611,
  [SMALL_STATE(76)] = 1624,
  [SMALL_STATE(77)] = 1637,
  [SMALL_STATE(78)] = 1650,
  [SMALL_STATE(79)] = 1659,
  [SMALL_STATE(80)] = 1672,
  [SMALL_STATE(81)] = 1685,
  [SMALL_STATE(82)] = 1698,
  [SMALL_STATE(83)] = 1711,
  [SMALL_STATE(84)] = 1724,
  [SMALL_STATE(85)] = 1737,
  [SMALL_STATE(86)] = 1750,
  [SMALL_STATE(87)] = 1763,
  [SMALL_STATE(88)] = 1776,
  [SMALL_STATE(89)] = 1789,
  [SMALL_STATE(90)] = 1802,
  [SMALL_STATE(91)] = 1810,
  [SMALL_STATE(92)] = 1818,
  [SMALL_STATE(93)] = 1826,
  [SMALL_STATE(94)] = 1836,
  [SMALL_STATE(95)] = 1846,
  [SMALL_STATE(96)] = 1856,
  [SMALL_STATE(97)] = 1866,
  [SMALL_STATE(98)] = 1876,
  [SMALL_STATE(99)] = 1886,
  [SMALL_STATE(100)] = 1893,
  [SMALL_STATE(101)] = 1900,
  [SMALL_STATE(102)] = 1907,
  [SMALL_STATE(103)] = 1914,
  [SMALL_STATE(104)] = 1921,
  [SMALL_STATE(105)] = 1928,
  [SMALL_STATE(106)] = 1935,
  [SMALL_STATE(107)] = 1942,
  [SMALL_STATE(108)] = 1949,
  [SMALL_STATE(109)] = 1956,
  [SMALL_STATE(110)] = 1963,
  [SMALL_STATE(111)] = 1970,
  [SMALL_STATE(112)] = 1977,
  [SMALL_STATE(113)] = 1984,
  [SMALL_STATE(114)] = 1991,
  [SMALL_STATE(115)] = 1998,
  [SMALL_STATE(116)] = 2005,
  [SMALL_STATE(117)] = 2012,
  [SMALL_STATE(118)] = 2019,
  [SMALL_STATE(119)] = 2026,
  [SMALL_STATE(120)] = 2033,
  [SMALL_STATE(121)] = 2040,
  [SMALL_STATE(122)] = 2047,
  [SMALL_STATE(123)] = 2054,
  [SMALL_STATE(124)] = 2061,
  [SMALL_STATE(125)] = 2068,
  [SMALL_STATE(126)] = 2075,
  [SMALL_STATE(127)] = 2082,
  [SMALL_STATE(128)] = 2089,
  [SMALL_STATE(129)] = 2096,
  [SMALL_STATE(130)] = 2103,
  [SMALL_STATE(131)] = 2110,
  [SMALL_STATE(132)] = 2117,
  [SMALL_STATE(133)] = 2124,
  [SMALL_STATE(134)] = 2131,
  [SMALL_STATE(135)] = 2138,
  [SMALL_STATE(136)] = 2145,
  [SMALL_STATE(137)] = 2152,
  [SMALL_STATE(138)] = 2159,
  [SMALL_STATE(139)] = 2166,
  [SMALL_STATE(140)] = 2173,
  [SMALL_STATE(141)] = 2180,
  [SMALL_STATE(142)] = 2187,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(130),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(93),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(94),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(127),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(126),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2), SHIFT_REPEAT(125),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_contract_declaration_repeat1, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 5),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_variable, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_variable, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 4),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2), SHIFT_REPEAT(60),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2), SHIFT_REPEAT(52),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_operator, 3, .production_id = 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_operator, 3, .production_id = 1),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(141),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(142),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_type, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constructor_declaration_repeat1, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 3),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_declaration, 5),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_declaration, 6),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [199] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2), SHIFT_REPEAT(98),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_type_repeat1, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_contract_declaration, 7),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_declaration_repeat1, 2), SHIFT_REPEAT(27),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2), SHIFT_REPEAT(37),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_alias, 1),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2), SHIFT_REPEAT(104),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entrypoint_modifier, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_modifier, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_declaration, 6),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 3),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 3),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 4),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_declaration, 7),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_declaration, 4),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__declaration, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 5),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__record_declaration, 4),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 4),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 2),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [327] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_aesophia_external_scanner_create(void);
void tree_sitter_aesophia_external_scanner_destroy(void *);
bool tree_sitter_aesophia_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_aesophia_external_scanner_serialize(void *, char *);
void tree_sitter_aesophia_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_aesophia(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_aesophia_external_scanner_create,
      tree_sitter_aesophia_external_scanner_destroy,
      tree_sitter_aesophia_external_scanner_scan,
      tree_sitter_aesophia_external_scanner_serialize,
      tree_sitter_aesophia_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
